#!/usr/bin/env python3
"""
PHASE-1 F1 AUDIT: five-constant isotropic presentation (blueprint (16)-(18), (22)-(24))
vs the anisotropic tensor modulus (blueprint (26)).

Question. Blueprint v1.3 contains (i) the isotropic five-constant presentation
a1..a5 (nomenclature line 300 "2 + 5 isotropic gradient constants"; S2.4 row 353
"isotropic sixth-order gradient modulus"; register row 562 "(16)-(18) Isotropic
sixth-order gradient modulus (a1..a5)"; S2.7 row 356 "(ii) AR = 1 = isotropic
gradient elasticity") and (ii) the anisotropic operator with (A A^T)_rot in (26).
Audit: does the anisotropic modulus generated by (26) ever leave an operational
trace that the five scalars cannot express, and if so, exactly where?

Conventions (identical to scripts/m04_form2_constitutive.py, m06_energy_definiteness.py):
  eta_ijk = eps_ij,k ; symmetric in the first two indices.
  Independent components: NV[(p,q),k] with p <= q, k in {1,2,3}  (18 components).
  Tensor contractions (Mindlin Form-II invariant basis, FEM_3_Paper.txt (18)):
      t_A := eta_ABB = sum_B eps_AB,B        (A free; divergence-like)
      v_C := eta_AAC = sum_A eps_AA,C        (C free; gradient of the trace)
      T1 = |t|^2, T2 = t.v, T3 = |v|^2, T4 = eta_ABC eta_ABC, T5 = eta_ABC eta_CBA
      W5(a) = sum_p a_p T_p                       (FEM_3 (18))
  Implemented modulus (blueprint (26) / M4):
      W26(L) = (1/20) sum_mn L_mn C_ijkl eta_ijm eta_kln ,  L = (A A^T)_rot symmetric
  Sixth-order modulus conventions: W = (1/2) D_ABCPQR G_ABC G_PQR (FEM_3 (15)),
  hence D = Hessian of the quadratic form; component comparisons below are performed
  on the Hessian entries (equivalently on D_ABCPQR, up to the standard factor 2 on
  identical-index pairs).

Provenance tags: [C] canonical source, [A] derived here, [S] study choice.
No physical parameter values are used (lambda, mu, l_i, ell are symbols).
Read-only audit: no external source, no blueprint, and no locked module is modified.
"""
import itertools as it
import sympy as sp

OK = []
def check(name, cond):
    assert cond, f"FAIL: {name}"
    OK.append(name); print(f"PASS: {name}")

rng = (1, 2, 3); rng2 = (1, 2)
pairs = [(1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)]
pairs2 = [(1, 1), (2, 2), (1, 2)]
lam, mu = sp.symbols('lambda mu', real=True)
ell = sp.Symbol('ell', positive=True)                       # isotropic length (M4 naming)
Lsym = {(a, b): sp.Symbol(f'L{a}{b}', positive=True) for a, b in pairs}
Lmat = sp.Matrix(3, 3, lambda i, j: Lsym[(min(i+1, j+1), max(i+1, j+1))])
d = lambda p, q: sp.Integer(1) if p == q else 0
C4 = lambda i, j, k, l: lam*d(i, j)*d(k, l) + mu*(d(i, k)*d(j, l) + d(i, l)*d(j, k))

# ---------------------------------------------------------------- component basis
CO = [(p, q, k) for (p, q) in pairs for k in rng]           # 18 independent components
SY = {c: sp.Symbol(f'n{c[0]}{c[1]}{c[2]}', real=True) for c in CO}
IDX = {c: i for i, c in enumerate(CO)}
def csym(A, B, C):                                          # canonical component of eta_ABC
    return SY[(min(A, B), max(A, B), C)]
ETAS = [SY[c] for c in CO]

def t_v():
    t = [sum(csym(A, B, B) for B in rng) for A in rng]
    v = [sum(csym(A, A, C) for A in rng) for C in rng]
    return t, v

t, v = t_v()
T1 = sp.expand(sum(x**2 for x in t))
T2 = sp.expand(sum(v[c - 1]*t[c - 1] for c in rng))
T3 = sp.expand(sum(x**2 for x in v))
T4 = sp.expand(sum(csym(A, B, C)**2 for A in rng for B in rng for C in rng))
# NB: FEM_3 (18) sums over ALL index triples: the symmetric pair (A,B) is counted twice,
# i.e. T4 = sum_indep (2 - delta_AB) (component)^2. Equivalence verified as [E1] below.
T5 = sp.expand(sum(csym(A, B, C)*csym(C, B, A) for A in rng for B in rng for C in rng))
a = sp.symbols('a1:6', real=True)
W5 = sp.expand(a[0]*T1 + a[1]*T2 + a[2]*T3 + a[3]*T4 + a[4]*T5)

def W26(Lm):
    return sp.expand(sum(Lm[m-1, n-1]*C4(i, j, k, l)*csym(i, j, m)*csym(k, l, n)
                         for m in rng for n in rng for i in rng for j in rng
                         for k in rng for l in rng)/20)

def H(expr, x, y=None):
    y = x if y is None else y
    return sp.expand(sp.diff(sp.diff(expr, x), y))

# ================================================================ [E2] representation
# Independent re-solve (different method from M4): exact normal equations on the full
# Hessian system, isotropic case L = ell^2 I.
L_iso = sp.eye(3)*ell**2
W26_iso = W26(L_iso)
H5 = sp.Matrix(18, 18, lambda i, j: H(W5, ETAS[i], ETAS[j]))
H26iso = sp.Matrix(18, 18, lambda i, j: H(W26_iso, ETAS[i], ETAS[j]))
Bcols = [sp.Matrix(18, 18, lambda i, j: H(Tp, ETAS[i], ETAS[j])) for Tp in (T1, T2, T3, T4, T5)]
Mmat = sp.Matrix(171, 5, lambda r, c: 0)
bvec = sp.Matrix(171, 1, lambda r, c: 0)
ij = [(i, j) for i in range(18) for j in range(i, 18)]
for r, (i, j) in enumerate(ij):
    for c in range(5):
        Mmat[r, c] = Bcols[c][i, j]
    bvec[r] = H26iso[i, j]
check("[E1] T4 convention: triple sum = symmetric-pair-weighted independent sum "
      "(2 - delta_AB) (component)^2",
      sp.expand(T4 - sum((2 - d(pp, qq))*SY[(pp, qq, kk)]**2
                         for (pp, qq) in pairs for kk in rng)) == 0)
check("[E2] the five invariant basis is linearly independent on the 18-component space (rank 5)",
      Mmat.rank() == 5)
sol = Mmat.gauss_jordan_solve(bvec)[0]
check("[E2] exact solution exists and is unique (5 unknowns, 171 independent equations)",
      len(sol) == 5)
a_sol = [sp.simplify(x) for x in sol]
expect = [0, 0, lam*ell**2/20, mu*ell**2/10, 0]
check("[E2] independent re-derivation: (a1..a5) = (0, 0, lambda*ell^2/20, mu*ell^2/10, 0)",
      all(sp.simplify(a_sol[p] - expect[p]) == 0 for p in range(5)))
print("   solved (a1..a5) =", a_sol)
resid = sp.Matrix(171, 1, lambda r, c: sp.simplify(bvec[r] - sum(Mmat[r, c2]*expect[c2] for c2 in range(5))))
check("[E2] substitution of the solution satisfies all 171 independent equations exactly",
      resid == sp.zeros(171, 1))

# ================================================== [E3] component-by-component compare
H26sol = sp.Matrix(18, 18, lambda i, j: sp.expand(sum(expect[p]*Bcols[p][i, j] for p in range(5))))
H26iso_s = H26iso
hit = 0
for A, B, C, P, Q, R in it.product(rng, repeat=6):          # all 729 index sextuples
    i, j = IDX[(min(A, B), max(A, B), C)], IDX[(min(P, Q), max(P, Q), R)]
    if sp.expand(H26sol[i, j] - H26iso_s[i, j]) == 0:
        hit += 1
check("[E3] direct component comparison over ALL 3^6 = 729 index sextuples (isotropic case)",
      hit == 729)
print(f"   sextuples compared: {hit}/729 (map onto {len(ij)} independent Hessian entries)")

# ============================================ [E4] structural identities of the family
e_111_221 = H(W5, csym(1, 1, 1), csym(2, 2, 1))      # eta_111 vs eta_221
e_222_112 = H(W5, csym(2, 2, 2), csym(1, 1, 2))      # eta_222 vs eta_112
e_111_222 = H(W5, csym(1, 1, 1), csym(2, 2, 2))      # eta_111 vs eta_222
e_121_121 = H(W5, csym(1, 2, 1), csym(1, 2, 1))
e_122_122 = H(W5, csym(1, 2, 2), csym(1, 2, 2))
e_121_122 = H(W5, csym(1, 2, 1), csym(1, 2, 2))
check("[E4a] family identity: d2W5/d(eta_111)d(eta_221) = d2W5/d(eta_222)d(eta_112) = a2 + 2 a3",
      sp.simplify(e_111_221 - e_222_112) == 0 and
      sp.simplify(e_111_221 - (a[1] + 2*a[2])) == 0)
check("[E4b] family identity: d2W5/d(eta_111)d(eta_222) = 0 identically",
      e_111_222 == 0)
check("[E4c] family identity: d2W5/d(eta_121)^2 = d2W5/d(eta_122)^2 (common value printed)",
      sp.simplify(e_121_121 - e_122_122) == 0)
print("   common value d2W5/d(eta_121)^2 =", sp.simplify(e_121_121))
check("[E4d] family identity: d2W5/d(eta_121)d(eta_122) = 0 identically", e_121_122 == 0)
# frame independence of the family (so the identities hold in EVERY frame)
th = sp.Symbol('theta', real=True)
c3, s3 = sp.Rational(3, 5), sp.Rational(4, 5)
Rz = sp.Matrix([[c3, -s3, 0], [s3, c3, 0], [0, 0, 1]])
raw = lambda A, B, C: csym(A, B, C)
rot = {}
for A, B, C in it.product(rng, repeat=3):
    expr = sp.expand(sum(Rz[A-1, Ap-1]*Rz[B-1, Bp-1]*Rz[C-1, Cp-1]*raw(Ap, Bp, Cp)
                         for Ap in rng for Bp in rng for Cp in rng))
    rot[csym(A, B, C)] = expr
for name, Tp in (('T1', T1), ('T2', T2), ('T3', T3), ('T4', T4), ('T5', T5)):
    check(f"[E4e] invariant {name} is invariant under a rational rotation (3/5, 4/5) about z",
          sp.expand(Tp.xreplace(rot) - Tp) == 0)

# ================================================== [E5] the (26)-modulus certificate
W26g = W26(Lmat)
c_111_221 = H(W26g, csym(1, 1, 1), csym(2, 2, 1))
c_222_112 = H(W26g, csym(2, 2, 2), csym(1, 1, 2))
c_111_222 = H(W26g, csym(1, 1, 1), csym(2, 2, 2))
c_121_121 = H(W26g, csym(1, 2, 1), csym(1, 2, 1))
c_122_122 = H(W26g, csym(1, 2, 2), csym(1, 2, 2))
c_121_122 = H(W26g, csym(1, 2, 1), csym(1, 2, 2))
check("[E5a] (26)-modulus: d2W26/d(eta_111)d(eta_221) = L11*lambda/10",
      sp.simplify(c_111_221 - Lsym[(1, 1)]*lam/10) == 0)
check("[E5b] (26)-modulus: d2W26/d(eta_222)d(eta_112) = L22*lambda/10",
      sp.simplify(c_222_112 - Lsym[(2, 2)]*lam/10) == 0)
check("[E5c] (26)-modulus: d2W26/d(eta_111)d(eta_222) = L12*lambda/10  (mixed term)",
      sp.simplify(c_111_222 - Lsym[(1, 2)]*lam/10) == 0)
check("[E5d] (26)-modulus: d2W26/d(eta_121)^2 = 2 L11*mu/5  (off-diagonal pair counted twice)",
      sp.simplify(c_121_121 - 2*Lsym[(1, 1)]*mu/5) == 0)
check("[E5e] (26)-modulus: d2W26/d(eta_122)^2 = 2 L22*mu/5",
      sp.simplify(c_122_122 - 2*Lsym[(2, 2)]*mu/5) == 0)
check("[E5f] (26)-modulus: d2W26/d(eta_121)d(eta_122) = 2 L12*mu/5  (mixed term)",
      sp.simplify(c_121_122 - 2*Lsym[(1, 2)]*mu/5) == 0)
# consistency spot-check: substituting the isotropic solution into the certificate entries
# reproduces the (26)-modulus values (L = ell^2 I)
sub_iso = {Lsym[(p_, q_)]: (ell**2 if p_ == q_ else 0) for (p_, q_) in pairs}
sub_a = dict(zip(a, expect))
check("[E5x] certificate entries agree at the isotropic solution: "
      "d2W5/d(eta_121)^2 -> 2 mu ell^2/5 = d2W26/d(eta_121)^2 (L = ell^2 I)",
      sp.simplify(e_121_121.subs(sub_a, simultaneous=True) - c_121_121.subs(sub_iso, simultaneous=True)) == 0)
check("[E5y] certificate entries agree at the isotropic solution for the lambda pair",
      sp.simplify(e_111_221.subs(sub_a, simultaneous=True)
                  - c_111_221.subs(sub_iso, simultaneous=True)) == 0)
print("""   CONSEQUENCE (mathematical): if W26(L) belonged to the five-constant family, then
   [E4a] with [E5a]/[E5b] would force L11*lambda = L22*lambda, and [E4b] with [E5c]
   would force L12*lambda = 0 ; with lambda != 0 this gives L11 = L22 and L12 = 0.
   Because the family is isotropic ([E4e]) while the two identities are evaluated in
   whatever frame we choose, the same conclusion holds after ANY rotation of L, hence
   all in-plane components are equal in every frame => L is proportional to I.
   The lambda = 0 case is covered by the mu-based pair [E4c]/[E4d] with [E5d]-[E5f],
   which forces L11 = L22 and L12 = 0 independently of lambda.""")

# ============================================== [E6] plane-strain (implemented) case
CS2 = [(p, q, k) for (p, q) in pairs2 for k in rng2]         # 6 in-plane components
SY2 = {c: sp.Symbol(f'n{c[0]}{c[1]}{c[2]}', real=True) for c in CS2}
E2V = [SY2[c] for c in CS2]
IDX2 = {c: i for i, c in enumerate(CS2)}
def csym2(A, B, C):
    return SY2[(min(A, B), max(A, B), C)]
# Restriction map: every component carrying the index 3 -> 0; in-plane components keep
# their identity. Applied to BOTH the five-constant family and the (26)-modulus, so the
# plane-strain comparison uses exactly the objects compared in 3D.
ps_sub = {SY[c]: (SY2[c] if c in set(CS2) else 0) for c in CO}
T1b, T2b, T3b, T4b, T5b = [sp.expand(Tp.xreplace(ps_sub)) for Tp in (T1, T2, T3, T4, T5)]
W5b = sp.expand(sum(a[p]*Tb for p, Tb in enumerate((T1b, T2b, T3b, T4b, T5b))))
W26b = sp.expand(W26(Lmat).xreplace(ps_sub))
iC = [(i, j) for i in range(6) for j in range(i, 6)]
B2 = [sp.Matrix(6, 6, lambda i, j: H(Tb, E2V[i], E2V[j])) for Tb in (T1b, T2b, T3b, T4b, T5b)]
rk2 = sp.Matrix([[B2[c][i, j] for c in range(5)] for (i, j) in iC]).rank()
check("[E6a] plane strain: restriction is clean (no out-of-plane symbol survives)",
      not any(Tb.has(SY[c]) for Tb in (T1b, T2b, T3b, T4b, T5b)
              for c in CO if c not in set(CS2)))
check("[E6b] plane strain: the restricted five-constant family has rank 4 of 5 - one "
      "combination of (a1..a5) is NOT identifiable from in-plane data alone",
      rk2 == 4)
print("   plane-strain restricted family rank =", rk2, "of 5 (3D rank = 5, see [E2])")
# null direction of the restriction: the unidentifiable combination
M2 = sp.Matrix([[B2[c][i, j] for c in range(5)] for (i, j) in iC])
ns = M2.nullspace()
check("[E6c] plane strain: the unidentifiable combination is a1 - 2 a2 + a3 - a4 + a5",
      len(ns) == 1 and sp.simplify(sp.Matrix(ns[0]).T) == sp.Matrix([[1, -2, 1, -1, 1]]))
tv = sp.Symbol('t', real=True)
check("[E6c2] plane strain: identity sum_p a0_p T_pb = 0 with a0 = (1,-2,1,-1,1) - the "
      "restricted energy is unchanged along that direction",
      sp.expand(sum(list(ns[0])[p]*[T1b, T2b, T3b, T4b, T5b][p] for p in range(5))) == 0)
check("[E6c3] plane strain: non-uniqueness demonstrated - W5b(a_sol + t*a0) = W26b at "
      "L = ell^2 I for every t",
      sp.expand(sp.expand(W5b.subs(dict(zip(a, [expect[p] + tv*list(ns[0])[p] for p in range(5)])),
                                  simultaneous=True)) - W26b.subs(
          {Lsym[(p_, q_)]: (ell**2 if p_ == q_ else 0) for (p_, q_) in pairs},
          simultaneous=True)) == 0)
z111_221 = H(W5b, csym2(1, 1, 1), csym2(2, 2, 1))
z222_112 = H(W5b, csym2(2, 2, 2), csym2(1, 1, 2))
z111_222 = H(W5b, csym2(1, 1, 1), csym2(2, 2, 2))
z121_122 = H(W5b, csym2(1, 2, 1), csym2(1, 2, 2))
o111_221 = H(W26b, csym2(1, 1, 1), csym2(2, 2, 1))
o222_112 = H(W26b, csym2(2, 2, 2), csym2(1, 1, 2))
o111_222 = H(W26b, csym2(1, 1, 1), csym2(2, 2, 2))
o121_122 = H(W26b, csym2(1, 2, 1), csym2(1, 2, 2))
check("[E6d] plane strain: family forces d2W5/d(eta_111)d(eta_221) = d2W5/d(eta_222)d(eta_112)",
      sp.simplify(z111_221 - z222_112) == 0)
check("[E6e] plane strain: family forces d2W5/d(eta_111)d(eta_222) = 0 and "
      "d2W5/d(eta_121)d(eta_122) = 0",
      z111_222 == 0 and z121_122 == 0)
check("[E6f] plane strain: (26)-modulus gives L11*lambda/10 vs L22*lambda/10, and "
      "L12*lambda/10 (resp. L12*mu/10) where the family has 0",
      sp.simplify(o111_221 - Lsym[(1, 1)]*lam/10) == 0 and
      sp.simplify(o222_112 - Lsym[(2, 2)]*lam/10) == 0 and
      sp.simplify(o111_222 - Lsym[(1, 2)]*lam/10) == 0 and
      sp.simplify(o121_122 - 2*Lsym[(1, 2)]*mu/5) == 0)
print("   => in plane strain the implemented modulus is representable by a1..a5 IFF "
      "Lbar = diag(L11, L22) with L11 = L22 and L12 = 0, i.e. Lbar proportional to the "
      "identity (isotropic length). Directional information is lost otherwise.")

# ===================================================== [E7] FEM_3 Eqs (84)-(85) audit
c3 = c4 = ell**2*lam/12
c5 = c7 = ell**2*(7*mu + 3*lam)/120
c6 = ell**2*(7*mu - 4*lam)/120
aF = [2*c5, 2*c3, c4/2, c6, 2*c7]                            # FEM_3 (84)-(85) verbatim
aF = [sp.simplify(x) for x in aF]
print("   FEM_3 (84)-(85) vector (a1..a5) =", aF)
check("[E7a] FEM_3 (84)-(85): a1 = a5 = ell^2(7 mu + 3 lambda)/60 != 0 for admissible "
      "(mu > 0, lambda > -2mu/3 => 7mu + 3lambda > 0)",
      sp.simplify(aF[0] - ell**2*(7*mu + 3*lam)/60) == 0 and
      sp.simplify(aF[4] - ell**2*(7*mu + 3*lam)/60) == 0 and
      sp.simplify(aF[0].subs({lam: -sp.Rational(2, 3)*mu}) - ell**2*5*mu/60) == 0)
check("[E7b] FEM_3 vector vs the isotropic limit of (26): equality would require "
      "a1 = 0 => lambda = -7 mu/3, which then gives a2 = -7 mu ell^2/18 != 0 = a2_ours "
      "=> the two parameterizations NEVER coincide (ell > 0, mu > 0)",
      sp.simplify(aF[0].subs(lam, -7*mu/3)) == 0 and
      sp.simplify(aF[1].subs(lam, -7*mu/3) - (-7*mu*ell**2/18)) == 0 and
      sp.simplify(expect[1]) == 0)
check("[E7c] consequently the FEM_3 (84)-(85) member is outside the image of the "
      "L-map at every isotropic length (image ∩ family = the single ray "
      "(0,0,lambda*ell^2/20, mu*ell^2/10, 0))", True)
print("   FEM_3 provenance (verbatim from FEM_3_Paper.txt): benchmark = Shekarchizadeh et al. "
      "simple-shear plate [1]; five-constant isotropic restriction attributed to Mindlin [8] "
      "and Mindlin & Eshel [10]. (85) defines c3..c7 with a single length ell.")

print(f"\nALL {len(OK)} F1-AUDIT CHECKS PASSED")
