#!/usr/bin/env python3
"""Science-preservation invariant checks (Task 15, PART 27).

Reads results/raw only; compares against the validated headline values of the
accepted studies.  Prints PASS/FAIL lines and writes
verification/INVARIANT_CHECK.md.  Exit code 0 iff all pass.
"""
import csv, os, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "results" / "raw"

def rows(f):
    return list(csv.DictReader([l for l in open(RAW / f) if not l.startswith("#")]))

def A(rs, k):
    import numpy as np
    return np.array([float(r[k]) for r in rs])

import numpy as np
checks = []
def chk(name, ok, detail):
    checks.append((name, bool(ok), detail))

# V2 elastic limit
kv = {}
coupled = []
for l in open(RAW / "v2_elastic_limit.csv"):
    l = l.strip()
    if l.startswith("#") or l.startswith("model,"):
        continue
    p = l.split(",")
    if len(p) == 2: kv[p[0]] = float(p[1])
    elif len(p) == 6: coupled.append((p[0], float(p[1]), float(p[3])))
chk("vP/v0 = 1", abs(kv["vP_over_v0"] - 1) < 1e-14, kv["vP_over_v0"])
chk("vS/v0 = 0.5", abs(kv["vS_over_v0"] - 0.5) < 1e-14, kv["vS_over_v0"])
rel = abs(kv["VR_over_vS_numerical"] - kv["VR_over_vS_analytic"]) / kv["VR_over_vS_analytic"]
chk("Rayleigh rel. err ~1.1e-11", rel < 2e-11, rel)
cA = [c[2] for c in coupled if c[0] == "A" and abs(c[1] - 1e-5) < 1e-9][0]
cB = [c[2] for c in coupled if c[0] == "B" and abs(c[1] - 1e-5) < 1e-9][0]
chk("coupled A quasi-static 0.62145378", abs(cA - 0.62145378) < 1e-7, cA)
chk("coupled B/C quasi-static 0.9326028", abs(cB - 0.9326028) < 1e-6, cB)

# resolution bench
rb = rows("resolution_bench.csv")[0]
chk("eps_Delta = 1.1299e-8", abs(float(rb["eps_Delta"]) - 1.129857263305e-8) < 1e-12, rb["eps_Delta"])
eps = float(rb["eps_Delta"])

# baseline
b = rows("study1_baseline.csv")
for m in "ABC":
    sel = [r for r in b if r["model"] == m]
    Om, V, Pw = A(sel, "Omega"), A(sel, "V"), A(sel, "P_w")
    if m == "A":
        chk("V_A(1e-3)=0.31072689", abs(V[0] - 0.3107268903703) < 1e-8, V[0])
        chk("V_A(1e3)=0.31072662", abs(V[-1] - 0.31072662) < 1e-7, V[-1])
        chk("Pw,A ~0.991", abs(Pw.mean() - 0.991) < 2e-3, Pw.mean())
    if m == "B":
        chk("V_B(1e-3)=0.46630123", abs(V[0] - 0.4663012299753) < 1e-8, V[0])

f4 = rows("fig4_deltas.csv")
dBC, dAC = A(f4, "Delta_BC"), A(f4, "Delta_AC")
chk("max Delta_BC ~9.48e-6", dBC.max() < 9.5e-6 and dBC.max() > 9.0e-6, dBC.max())
flr = eps / 0.4663
chk("95/121 below floor", int((dBC < flr).sum()) == 95, int((dBC < flr).sum()))
chk("Delta_AC ~0.334", 0.33 < dAC.max() < 0.34, dAC.max())

# V3 gates + branch identity
v3 = rows("v3_model_limits.csv")
gA = np.abs(A(v3, "V_C_Dw14") / A(v3, "V_A") - 1).max()
gB = np.abs(A(v3, "V_C_rhow0") / A(v3, "V_B") - 1).max()
chk("C->A gate ~1.11e-9", gA < 2e-9, gA)
chk("C->B gate ~3.27e-9", gB < 4e-9, gB)
i1000 = [i for i, r in enumerate(v3) if abs(float(r["Omega"]) - 1e3) < 1][0]
VC0 = float(v3[i1000]["V_C_Dw0"]); VA = float(v3[i1000]["V_A"])
chk("branch identity @Om=1000: V_C(Dw->0)=0.3107266158 (NOT 0.467)",
    0.310 < VC0 < 0.311 and abs(VC0 - VA) < 1e-9, (VC0, VA, abs(VC0 - VA)))
ev = np.abs(A(v3, "V_C_Dw0") / A(v3, "V_A") - 1)
Om3 = A(v3, "Omega")
chk("evidence 71/121 <=1e-6 for Om>=0.31622776602",
    int(((ev <= 1e-6) & (Om3 >= 0.31622776602)).sum()) == 71,
    int(((ev <= 1e-6) & (Om3 >= 0.31622776602)).sum()))

# thermal
t6 = rows("fig6_tau.csv")
dT = A(t6, "Delta_T")
chk("max Delta_T ~7.88e-5", 7.7e-5 < dT.max() < 8.0e-5, dT.max())

# BC
f7 = rows("fig7_bc_summary.csv")
dvC = A(f7, "dV_over_V_C")
chk("phason-BC effect <=8.06e-6", 8.0e-6 < dvC.max() < 8.1e-6, dvC.max())

# penetration scaling (Fig 11b support)
for m, tol in (("A", 1e-4), ("B", 1e-3), ("C", 1e-3)):
    sel = [r for r in b if r["model"] == m]
    pr = A(sel, "Omega") * A(sel, "delta_pen")
    chk(f"Om*delta* flat ({m})", np.abs(pr - pr.mean()).max() / pr.mean() < tol,
        (pr.mean(), np.abs(pr - pr.mean()).max() / pr.mean()))

lines = ["# INVARIANT_CHECK.md (generated by verify_invariants.py)", ""]
allok = True
for name, ok, det in checks:
    allok &= ok
    lines.append(f"- [{'PASS' if ok else 'FAIL'}] {name} :: {det}")
lines.append("")
lines.append("OVERALL: " + ("PASS" if allok else "FAIL"))
open(ROOT / "verification" / "reports" / "INVARIANT_CHECK.md", "w").write("\n".join(lines) + "\n")
print("invariants:", "PASS" if allok else "FAIL", f"({sum(c[1] for c in checks)}/{len(checks)})")
sys.exit(0 if allok else 1)
