#!/usr/bin/env python3
"""Top-level reproduction driver for Research Paper 1.

Modes
-----
python3 run_all.py                reproduce from the SHIPPED raw data:
                                  env check -> invariant checks -> figures ->
                                  manuscript compile (x2) -> report
python3 run_all.py --check-only   env + invariant checks only
python3 run_all.py --from-scratch additionally run the solver drivers and the
                                  validation tests first (full production;
                                  slower; regenerates results/raw/*)

No hidden dependencies: all paths resolve relative to this file.
"""
import os, shutil, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PY = sys.executable

def run(cmd, **kw):
    print(">>", " ".join(str(c) for c in cmd))
    return subprocess.run([str(c) for c in cmd], cwd=ROOT, **kw)

def env_check():
    ok = True
    print("== environment ==")
    print("python:", sys.version.split()[0])
    for mod in ("numpy", "matplotlib"):
        try:
            __import__(mod); print(f"{mod}: OK")
        except ImportError:
            print(f"{mod}: MISSING"); ok = False
    tex = shutil.which("pdflatex")
    print("pdflatex:", tex or "MISSING (manuscript compile will be skipped)")
    return ok

def verify():
    print("== invariant checks (science preservation) ==")
    r = run([PY, "verification/verify_invariants.py"])
    return r.returncode == 0

def figures():
    print("== figure generation (programmatic, raw-data only) ==")
    r = run([PY, "figures/make_all_figures.py"])
    return r.returncode == 0

def compile_manuscript():
    if not shutil.which("pdflatex"):
        print("pdflatex missing: skipping compile")
        return None
    print("== manuscript compilation (2 passes) ==")
    ms = ROOT / "manuscript"
    # keep the journal-source figure copies in sync with figures/output
    (ms / "figures").mkdir(exist_ok=True)
    for f in (ROOT / "figures" / "output").glob("fig*.pdf"):
        shutil.copy2(f, ms / "figures" / f.name)
    for i in range(5):
        subprocess.run(["pdflatex", "-interaction=nonstopmode",
                        "FINAL_MANUSCRIPT.tex"], cwd=ms,
                       stdout=subprocess.DEVNULL)
        logchk = (ms / "FINAL_MANUSCRIPT.log").read_text(errors="ignore")
        if i >= 1 and "Rerun to get cross-references right" not in logchk:
            break
    log = (ms / "FINAL_MANUSCRIPT.log").read_text(errors="ignore")
    errs = log.count("\n!")
    warns = log.count("LaTeX Warning")
    und = log.count("undefined")
    pages = "?"
    try:
        from pypdf import PdfReader
        pages = len(PdfReader(str(ms / "FINAL_MANUSCRIPT.pdf")).pages)
    except Exception:
        pi = shutil.which("pdfinfo")
        if pi:
            out = subprocess.run([pi, str(ms / "FINAL_MANUSCRIPT.pdf")],
                                 capture_output=True, text=True).stdout
            for l in out.splitlines():
                if l.startswith("Pages:"): pages = l.split()[1]
    nfig = len(list((ROOT / "figures" / "output").glob("fig*.pdf")))
    tex = (ms / "FINAL_MANUSCRIPT.tex").read_text()
    ntab = tex.count("\\begin{table}")
    return dict(errors=errs, warnings=warns, undefined=und, pages=pages,
                figures=nfig, tables=ntab)

def from_scratch():
    print("== full production (solver drivers + validation tests) ==")
    env = dict(os.environ, PYTHONPATH=str(ROOT))
    for d in ("study1_baseline", "study2_friction_map", "study3_thermal",
              "study_bc", "roots_diag"):
        r = subprocess.run([PY, f"drivers/{d}.py"], cwd=ROOT, env=env)
        if r.returncode != 0:
            print(f"driver {d} FAILED"); return False
    for t in sorted((ROOT / "tests").glob("V*/test_*.py")):
        r = subprocess.run([PY, str(t)], cwd=ROOT, env=env)
        if r.returncode != 0:
            print(f"test {t.name} FAILED"); return False
    return True

def report(inv_ok, fig_ok, cm):
    print("== writing REPRODUCTION_REPORT.md ==")
    L = ["# REPRODUCTION_REPORT.md (generated by run_all.py)", ""]
    L.append(f"- invariant checks: {'PASS' if inv_ok else 'FAIL'}")
    L.append(f"- figure regeneration: {'PASS' if fig_ok else 'FAIL'}")
    if cm:
        L.append(f"- manuscript: {cm['pages']} pages, {cm['errors']} errors, "
                 f"{cm['warnings']} LaTeX warnings, {cm['undefined']} undefined refs")
        L.append(f"- figures embedded/available: {cm['figures']}; tables: {cm['tables']}")
        L.append(f"- manuscript compilation: "
                 f"{'PASS' if cm['errors'] == 0 else 'FAIL'}")
    else:
        L.append("- manuscript compilation: SKIPPED (no pdflatex)")
    (ROOT / "REPRODUCTION_REPORT.md").write_text("\n".join(L) + "\n")

def main():
    args = sys.argv[1:]
    ok = env_check()
    if "--from-scratch" in args:
        ok &= from_scratch()
    inv = verify()
    if "--check-only" in args:
        report(inv, False, None)
        sys.exit(0 if inv else 1)
    fig = figures()
    cm = compile_manuscript()
    report(inv, fig, cm)
    good = ok and inv and fig and (cm is None or cm["errors"] == 0)
    print("REPRODUCTION:", "PASS" if good else "FAIL")
    sys.exit(0 if good else 1)

if __name__ == "__main__":
    main()
