"""Validation against the published anchor (sec:anchor).

Implements:
  calc:repro      procedure
  eq:sigmad       digitisation noise floor (read from the archived digitisation)
  NRMSE metric    100 * RMSE / (max-min) of the PUBLISHED curve

The digitised published curves are INPUT DATA, not generated by this program.
They are loaded from data/ and originate from the archived digitisation of the
anchor's figures.
"""
from __future__ import annotations
from pathlib import Path
import numpy as np

# Digitised published curves are read from the central data/input tree.
from src.io import INPUT_DIR
DATA = INPUT_DIR

# calc:repro / tab:anchor-params, all LIT from Kovacs2018
ANCHOR_CASES = {
    "fig3": dict(tau_q=0.02, kappa2=0.02, tmax=1.0, tau_D=0.04),
    "fig5": dict(tau_q=0.02, kappa2=0.20, tmax=2.0, tau_D=0.04),
}
FIG2 = dict(tau_q=0.02, kappa2=0.02, tau_D=0.04, N_list=(1, 3, 10, 40))


def load_digitised(name):
    """Published curve digitised from the anchor figure. INPUT DATA."""
    d = np.load(DATA / "digitised.npy", allow_pickle=True).item()[name]
    return d["x"], d["ymean"], float(d["sigma_d"])


def load_fig2():
    """Coarse (col_step=4) digitisation, retained for reference."""
    return np.load(DATA / "gate4_fig2.npy", allow_pickle=True).item()


def load_fig2_despeckled():
    """Authoritative Fig.2 input: col_step=2 digitisation with gridline
    despeckle, 1999 assignable points, full range 1.6976.

    Provenance: regenerated by scripts/regenerate_fig2_digitisation.py from the
    anchor figure image. Dashed gridlines leave isolated dark pixels that a
    column tracer reads as curve points; a real curve is continuous, so points
    without neighbours in adjacent columns are removed. This is INPUT DATA
    (a digitisation of a published figure), not a program output."""
    return np.load(DATA / "fig2_digitised_despeckled.npy", allow_pickle=True).item()


FIG2_ASSIGN_RADIUS = 0.06   # calc:repro nearest-curve assignment radius


def metrics(pub, ours, sigma_d=None):
    r = np.asarray(ours) - np.asarray(pub)
    rmse = float(np.sqrt(np.mean(r ** 2)))
    rng = float(np.max(pub) - np.min(pub))
    out = {"n": int(len(pub)), "rmse": rmse, "nrmse_pct": 100.0 * rmse / rng,
           "emax": float(np.max(np.abs(r))), "range": rng}
    if sigma_d:
        out["sigma_d"] = sigma_d
        out["rmse_over_sigma_d"] = rmse / sigma_d
        out["within_2sigma_pct"] = float(100.0 * np.mean(np.abs(r) <= 2 * sigma_d))
    return out
