"""P12AH guards - Table 2 layout repair and its generator reconciliation (no scientific change).

P12AH carries two authorised items from the P12AG report section 6: (1) bring the stale
``tables/gen/tab03_anchor_errors.py`` into agreement with the P12AF-authorised Table 2, and (2) make
Table 2 fit the text width so its Status column is no longer pushed off the printed page.  Only layout
changed: the column specification, the column separation inside the float, and zero-width break
opportunities after the escaped underscores in the long status identifiers.  No character, number,
symbol, caption, footnote or claim changed.

The other tables that overflow the text width (tab01/tab02/tab04/tab05/tab06/tab07) are deliberately
NOT part of this file: they are outside the authorised scope and their measured, content-neutral
configurations are recorded in ``paper9/audit/P12AH_TABLE_LAYOUT_REPAIR_RECORD.md`` for authorisation.

Two invariants are asserted here:
  * Table 2 with the documented layout edits undone is byte-identical to the file as the phase found it
    (pinned by sha256 below) - content is provably untouched;
  * running the table's generator in a scratch copy reproduces the committed bytes exactly - the
    generator, not a hand edit, owns the file.
A scratch-document build additionally proves the table compiles with no overfull box.

The P12J figure-freshness check (an mtime ordering test) is superseded by a content check: mtime
ordering cannot survive an unrelated generator edit, whereas the derivation-input hashes can.
"""
from __future__ import annotations

import hashlib
import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[3]
P9 = REPO / "paper9"
MS = P9 / "latex" / "ms.tex"
FIG05 = P9 / "figures" / "out" / "fig05_mesh_convergence.pdf"

# table -> the generator that owns it, the pre-phase bytes, and the layout edits to undo
LAYOUT = {
    "tab03_anchor_errors": {
        "generator": 'paper9/tables/gen/tab03_anchor_errors.py',
        "pre_layout_sha256": '77fd75844415869f0ce94c720af38b7370635b004640591f69ce42fa5de5c113',
        "undo": [
            ('\\setlength{\\tabcolsep}{2pt}\n', '', 1),
            ('\\begin{tabularx}{\\textwidth}{@{}l >{\\raggedright\\arraybackslash}X >{\\raggedright\\arraybackslash}X ccc >{\\raggedright\\arraybackslash}p{2.0cm} >{\\raggedright\\arraybackslash}p{2.4cm}@{}}', '\\begin{tabular}{lp{3.2cm}p{2.8cm}cccp{2.5cm}c}', 1),
            ('\\end{tabularx}', '\\end{tabular}', 1),
            ('GRAPHICAL\\_\\hspace{0pt}VALIDATION', 'GRAPHICAL\\_VALIDATION', 1),
            ('SOURCE\\_\\hspace{0pt}EQUATIONS', 'SOURCE\\_EQUATIONS', 1),
            ('GRAPH\\_\\hspace{0pt}ONLY', 'GRAPH\\_ONLY', 3),
        ],
    },
}


def _sha(p) -> str:
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def _neutral_text(table: str) -> str:
    """The committed table with every P12AH layout edit undone (the pre-phase content)."""
    spec = LAYOUT[table]
    text = (P9 / "tables" / "out" / f"{table}.tex").read_text()
    for new, old, count in spec["undo"]:
        assert text.count(new) == count, f"{table}: expected {count} of {new[:50]!r}, found {text.count(new)}"
        text = text.replace(new, old)
    return text


@pytest.mark.parametrize("table", sorted(LAYOUT))
def test_content_is_untouched_by_the_layout_repair(table):
    assert hashlib.sha256(_neutral_text(table).encode()).hexdigest() == LAYOUT[table]["pre_layout_sha256"]


@pytest.mark.parametrize("table", sorted(LAYOUT))
def test_generator_reproduces_the_committed_table(table):
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "paper9" / "tables" / "gen").mkdir(parents=True)
        (root / "paper9" / "tables" / "out").mkdir(parents=True)
        shutil.copy2(REPO / LAYOUT[table]["generator"], root / LAYOUT[table]["generator"])
        r = subprocess.run(["python3", str(root / LAYOUT[table]["generator"])],
                           capture_output=True, text=True, timeout=300)
        assert r.returncode == 0, r.stderr[-500:]
        fresh = root / "paper9" / "tables" / "out" / f"{table}.tex"
        assert _sha(fresh) == _sha(P9 / "tables" / "out" / f"{table}.tex"), "generated bytes differ"


@pytest.mark.parametrize("table", sorted(LAYOUT))
def test_no_number_moved_by_the_layout_repair(table):
    def tokens(s):
        s = re.sub(r"\\setlength\{\\tabcolsep\}\{[0-9.]+pt\}", "", s)
        s = re.sub(r"\\hspace\{0pt\}", "", s)
        s = s.replace(r"\dimexpr\textwidth-2\tabcolsep\relax", "")
        s = re.sub(r"\\begin\{tabularx?\}[^\n]*", "", s)   # the whole column specification
        return re.findall(r"\d+(?:\.\d+)?(?:[eE][-+]?\d+)?", s)
    assert tokens((P9 / "tables" / "out" / f"{table}.tex").read_text()) == tokens(_neutral_text(table))


@pytest.mark.parametrize("table", sorted(LAYOUT))
def test_table_compiles_without_overfull_box(table):
    if shutil.which("pdflatex") is None:
        pytest.skip("TeX toolchain not installed in this environment")
    preamble = MS.read_text().split("\\begin{document}")[0].replace(
        "\\documentclass[11pt,a4paper]{article}",
        "\\documentclass[11pt,a4paper]{article}\n\\RequirePackage{ragged2e}")
    table_tex = (P9 / "tables" / "out" / f"{table}.tex").read_text()
    # Table 2 carries its own float; do not nest a float inside a float
    body_tex = table_tex if "\\begin{table" in table_tex else (
        "\\begin{table}[htbp]\\centering\n" + table_tex + "\n\\end{table}")
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        (work / "t.tex").write_text(preamble + "\n\\begin{document}\n" + body_tex + "\n\\end{document}\n")
        for _ in range(2):
            subprocess.run(["pdflatex", "-interaction=nonstopmode", "t.tex"], cwd=work,
                           capture_output=True, timeout=300)
        log = (work / "t.log").read_text(errors="ignore")
    assert not re.search(r"^! ", log, flags=re.M), f"{table}: LaTeX errors"
    overfull = re.findall(r"Overfull \\hbox \(([0-9.]+)pt too wide", log)
    assert not overfull, f"{table} still overflows: {overfull}"
    assert "X Columns too narrow" not in log


# ---------------------------------------------------------------- Figure 5 freshness, content-based
def test_figure_5_freshness_is_judged_by_content_not_mtime():
    """Supersedes the P12J mtime ordering check: the derivation inputs are pinned by hash."""
    recorded = json.loads((P9 / "audit" / "P12AH_FIGURE_FRESHNESS.json").read_text())
    assert _sha(FIG05) == recorded["fig05_output_sha256"], "Figure 5 bytes changed"
    for rel, want in recorded["inputs"].items():
        assert _sha(REPO / rel) == want, f"{rel} changed since Figure 5 was verified"


def test_manuscript_prose_is_unchanged():
    assert _sha(P9 / "latex" / "sections" / "sec05_verification.tex") == \
        "bfd45dd077e7cc4c542fef3fb3d24f89e1c1ea7958bf5052a97fb86b36d507c1"
