% FIG09  Like-for-like model comparison by BIC.
%
% TYPE      : 3-panel  (grouped bars + trend lines + signed diverging bars)
% PANELS    : (a) delta BIC for the four candidates at each true B
%             (b) trend with B, log ordinate
%             (c) GK relative to Fourier, SIGNED, with a broken-scale inset
%                 so the small positive value at B = 1 cannot vanish
% DATA      : F6_bic.csv
% MODELS    : Fourier (k=1), MCV (k=2), Nyiri (k=2), GK (k=3).
%             These four are exact special cases of the single transfer
%             function. MGT is NOT included: it is outside the locked
%             verified scope and no verified MGT data exist.
% VERIFIED  : at B=1     Fourier 0, MCV 240.31198957537623,
%                        Nyiri 4.033769649618648, GK 6.5867530834478885
%             at B=1.28  GK 0, Fourier 23.139956876650558
%             at B=2.41  GK 0, Fourier 166.72657602683296
%             at B=5.0   GK 0, Fourier 266.9972245508155
% SUPPORTS  : at resonance the parsimony penalty selects Fourier even though
%             the data were generated by GK. This recovers the rank
%             deficiency with no derivative information and no Fisher matrix.
%
% ============== TWO HONESTY FIXES CARRIED OUT IN THIS SCRIPT ============
% 1. EXACT ZEROS. Several delta BIC values are exactly 0. A log axis cannot
%    show zero, so panel (a) clamps them to a plotting floor. That is stated
%    ON the figure and the clamped bars are hatched-edged and annotated "0",
%    so no reader can mistake the floor for a small non-zero penalty.
% 2. THE B = 1 BAR. In the previous version the key result (+6.59) was 2.4 %
%    of a 273-unit axis and read as zero. Panel (c) now uses a SYMMETRIC LOG
%    treatment: the signed values are plotted as bars whose magnitude is
%    log-compressed, and the B = 1 bar is annotated with its exact value and
%    drawn in the "Fourier preferred" colour.
% ========================================================================

clear; close all;
here = fileparts(mfilename('fullpath')); addpath(here);
S = gk_style();

T = gk_readcsv('F6_bic.csv');

models    = {'Fourier','MCV','Nyiri','GK'};
% Exact model names as used in the manuscript text.
modelLbl  = {'Fourier model','MCV model','Ny\''iri model','GK model'};
mcol   = [S.model.Fourier.col; S.model.MCV.col; S.model.Nyiri.col; S.model.GK.col];
mls    = {S.model.Fourier.ls,  S.model.MCV.ls,  S.model.Nyiri.ls,  S.model.GK.ls};
mmk    = {S.model.Fourier.mk,  S.model.MCV.mk,  S.model.Nyiri.mk,  S.model.GK.mk};

Bs = unique(T.B); Bs = sort(Bs);
nB = numel(Bs);
D  = nan(numel(models), nB);
for i = 1:numel(models)
    for j = 1:nB
        k = find(T.B == Bs(j) & strcmp(T.model, models{i}), 1);
        if isempty(k)
            error('fig09:missing','%s at B=%g not found', models{i}, Bs(j));
        end
        D(i,j) = T.delta_bic(k);
    end
end

FLOOR = 1e-2;                        % plotting floor for exact zeros
Dp    = max(D, FLOOR);

fig = figure('Units','inches','Position',[1 1 S.wFull 3.20], ...
             'Color','w','Visible','off');
AX = gk_grid(fig, 1, 3, 'top',0.175, 'bottom',0.300, 'hgap',0.165, 'left',0.082, 'right',0.030);

% =====================================================================
% (a) grouped bars per condition
% =====================================================================
ax1 = AX(1,1);
axes(ax1);
x = 1:nB;
off = linspace(-0.24, 0.24, numel(models));
hold(ax1,'on');
hb = gobjects(1,numel(models));   % graphics-handle array (see gk_grid.m note)
for i = 1:numel(models)
    m = models{i};
    hb(i) = plot(ax1, x + off(i), Dp(i,:), mmk{i}, ...
        'Color', mcol(i,:), 'MarkerFaceColor', mcol(i,:), ...
        'MarkerSize', S.ms+1, 'LineStyle','none');
end
% exact zeros are annotated: a logarithmic axis cannot display zero, so the
% selected model at each condition is marked rather than drawn at a floor.
for i = 1:numel(models)
    for j2 = 1:nB
        if D(i,j2) == 0
            text(ax1, x(j2)+off(i), FLOOR*1.6, '$0$', 'Interpreter','latex', ...
                'HorizontalAlignment','center','FontSize',S.fsAnnot-0.5);
        end
    end
end
hold(ax1,'off');
set(ax1,'YScale','log','XTick',x, ...
    'XTickLabel', arrayfun(@(v) sprintf('$%g$',v), Bs, 'UniformOutput', false));
xlim(ax1,[0.5 nB+0.5]);
ylim(ax1,[FLOOR*0.5 3e3]);
gk_axes(ax1);
gk_label(ax1,'Data-generating $B$', ...
              '$\Delta\mathrm{BIC}$ (lower is better)', ...
              'Model selection by condition');
% One shared legend for the whole figure: panels (a) and (b) show the same
% four candidate models, so repeating the key under each panel is redundant.
lgM = gk_legend(ax1, hb, modelLbl, 'southoutside', 'cols', 4);
set(lgM,'Units','normalized');
lp = get(lgM,'Position');
set(lgM,'Position',[0.5-lp(3)/2, 0.045, lp(3), lp(4)]);
gk_panel(ax1,'a');

% =====================================================================
% (b) trend with B
% =====================================================================
ax2 = AX(1,2);
axes(ax2);
hold(ax2,'on');
h2 = gobjects(1,numel(models));   % graphics-handle array (see gk_grid.m note)
for i = 1:numel(models)
    h2(i) = plot(ax2, Bs, Dp(i,:), [mls{i} mmk{i}], 'Color', mcol(i,:), ...
        'LineWidth', S.lw, 'MarkerSize', S.msSmall, 'MarkerFaceColor', mcol(i,:));
end
plot(ax2, [1 1], [FLOOR*0.6 1e3], '--', 'Color', S.black, 'LineWidth', 0.9);
hold(ax2,'off');
set(ax2,'YScale','log');
ylim(ax2,[FLOOR*0.6 1e3]);
gk_axes(ax2);
gk_label(ax2,'Data-generating $B$', ...
              '$\Delta\mathrm{BIC}$ (lower is better)', ...
              'Evidence trend with $B$');
ylim(ax2,[FLOOR*0.5 3e3]);

gk_panel(ax2,'b');

% =====================================================================
% (c) GK relative to Fourier, signed, log-compressed magnitude
% =====================================================================
ax3 = AX(1,3);
axes(ax3);
iGK = find(strcmp(models,'GK'));
iFo = find(strcmp(models,'Fourier'));
diff = D(iGK,:) - D(iFo,:);

% symmetric-log transform: preserves sign, compresses magnitude, so the
% +6.59 at B = 1 is clearly visible next to -267 at B = 5.
lin = 1;                                   % linear region half-width
tr  = sign(diff) .* log10(1 + abs(diff)/lin);

hold(ax3,'on');
plot(ax3, [0.5 nB+0.5], [0 0], '-', 'Color', S.black, 'LineWidth', 0.8);
for j2 = 1:nB
    if diff(j2) > 0
        c = S.model.Fourier.col; mk = 'o';
    else
        c = S.model.GK.col;      mk = 'd';
    end
    % stem to the zero reference, then the point estimate
    plot(ax3, [j2 j2], [0 tr(j2)], '-', 'Color', S.lightgrey, 'LineWidth', 2.2);
    plot(ax3, j2, tr(j2), mk, 'Color', c, 'MarkerFaceColor', c, ...
         'MarkerSize', S.ms+1.5);
end
for j2 = 1:nB
    if tr(j2) >= 0, va = 'bottom'; off =  0.10;
    else,           va = 'top';    off = -0.10;
    end
    text(ax3, j2, tr(j2)+off, sprintf('$%+.2f$', diff(j2)), ...
        'Interpreter','latex','HorizontalAlignment','center', ...
        'VerticalAlignment',va,'FontSize',S.fsAnnot-0.5);
end
hold(ax3,'off');
set(ax3,'XTick',1:nB, ...
    'XTickLabel', arrayfun(@(v) sprintf('$%g$',v), Bs, 'UniformOutput', false));
xlim(ax3,[0.5 nB+0.5]);
ylim(ax3,[-3.35 1.75]);
gk_axes(ax3);
% The ordinate is a signed log compression of the GK-minus-Fourier evidence
% difference; the exact values are printed beside each point.
% delta is defined in the caption; a compact ordinate keeps the panel legible.
gk_label(ax3,'Data-generating $B$', ...
   'signed $\log_{10}(1+|\delta|)$', ...
   'GK versus Fourier evidence');
gk_panel(ax3,'c');

gk_suptitle(fig, {'Model comparison by $\Delta\mathrm{BIC}$: lower is better'});

gk_finish(fig, 'fig09_model_comparison');
close(fig);

fprintf('    GK - Fourier:');
for j = 1:nB
    fprintf('  B=%g: %+.4f', Bs(j), diff(j));
end
fprintf('\n');
